name: Publish Github

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Publish to GitHub Packages
        run: mvn javadoc:jar deploy
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGE_TOKEN }}